<script src="./../../../../Public/admin/plugins/jquery/jquery.min.js"></script>
<script src="./../../../../Public/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="./../../../../Public/admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<script src="./../../../../Public/admin/dist/js/adminlte.js"></script>
<script src="./../../../../Public/admin/dist/js/adminlte.min.js?v=3.2.0"></script>
<script src="./../../../../Public/admin/plugins/jquery-mousewheel/jquery.mousewheel.js"></script>
<script src="./../../../../Public/admin/plugins/raphael/raphael.min.js"></script>
<script src="./../../../../Public/admin/plugins/jquery-mapael/jquery.mapael.min.js"></script>
<script src="./../../../../Public/admin/plugins/jquery-mapael/maps/usa_states.min.js"></script>
<script src="./../../../../Public/admin/plugins/chart.js/Chart.min.js"></script>
<script src="./../../../../Public/admin/dist/js/demo.js"></script>
<script src="./../../../../Public/admin/dist/js/pages/dashboard2.js"></script>
<script src="./../../../../Public/admin/plugins/jsgrid/demos/db.js"></script>
<script src="./../../../../Public/admin/plugins/jsgrid/jsgrid.min.js"></script>
<script src="./../../../../Public/admin/plugins/daterangepicker/daterangepicker.js"></script>
<script src="./../../../../Public/admin/plugins/inputmask/jquery.inputmask.min.js"></script>
<script src="./../../../../Public/admin/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
